import React from 'react';
import { useNavigate } from 'react-router-dom';
import { 
  CheckCircle2, 
  Sparkles, 
  AlertTriangle, 
  ArrowRight, 
  ArrowLeft, 
  Sun, 
  Moon, 
  FileCheck2, 
  ShieldCheck,
  Bot
} from 'lucide-react';
import PageHeader from '../components/PageHeader';
import { initialPatientData } from '../data/patientData';

export default function AIResult() {
  const navigate = useNavigate();
  const rx = initialPatientData.extractedPrescription;

  return (
    <div className="ai-result-container animate-fade-in">
      <PageHeader
        title="AI Prescription Analysis"
        subtitle="Extracted entities and automated clinical schedule generated by MediTrace OCR."
        showBackToDashboard={true}
      />

      {/* SUCCESS PROCESSING BANNER */}
      <div className="ai-success-banner">
        <div className="ai-success-left">
          <div className="ai-success-icon">
            <CheckCircle2 size={26} />
          </div>
          <div>
            <h3>Analysis Complete</h3>
            <p>Your prescription has been successfully processed.</p>
          </div>
        </div>

        <div style={{ display: 'flex', alignItems: 'center', gap: '0.6rem' }}>
          <span className="badge badge-success">Confidence: {rx.aiConfidence}</span>
          <span className="badge badge-info">OCR Engine v2.4</span>
        </div>
      </div>

      {/* EXTRACTED INFORMATION CARDS */}
      <div>
        <div className="section-title-wrap">
          <h3 className="section-title">
            <FileCheck2 size={18} color="#0284c7" />
            <span>Extracted Clinical Data</span>
          </h3>
          <span style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>
            Verified against Dr. Arvind Sharma's signature
          </span>
        </div>

        <div className="extracted-grid">
          <div className="extracted-card">
            <div className="extracted-label">Patient</div>
            <div className="extracted-value">{rx.patient}</div>
          </div>

          <div className="extracted-card">
            <div className="extracted-label">Disease</div>
            <div className="extracted-value">{rx.disease}</div>
          </div>

          <div className="extracted-card">
            <div className="extracted-label">Medicine</div>
            <div className="extracted-value" style={{ color: 'var(--primary)' }}>{rx.medicine}</div>
          </div>

          <div className="extracted-card">
            <div className="extracted-label">Dosage</div>
            <div className="extracted-value">{rx.dosage}</div>
          </div>

          <div className="extracted-card">
            <div className="extracted-label">Frequency</div>
            <div className="extracted-value">{rx.frequency}</div>
          </div>

          <div className="extracted-card">
            <div className="extracted-label">Duration</div>
            <div className="extracted-value">{rx.duration}</div>
          </div>
        </div>
      </div>

      {/* AI MEDICATION ASSISTANT */}
      <div className="ai-assistant-card">
        <div className="ai-assistant-header">
          <div className="ai-assistant-title">
            <Bot size={22} />
            <span>AI Medication Assistant</span>
          </div>
          <span className="badge badge-info">LLM Analysis</span>
        </div>

        <p style={{ fontSize: '0.95rem', color: 'var(--text-secondary)', lineHeight: 1.55 }}>
          "{rx.aiInsight}"
        </p>

        {/* MEDICATION SCHEDULE */}
        <div>
          <h4 style={{ fontSize: '0.95rem', fontWeight: 700, marginBottom: '0.75rem', color: 'var(--text-main)' }}>
            Medication Schedule
          </h4>

          <div className="schedule-grid">
            <div className="schedule-item">
              <Sun size={24} color="#f59e0b" />
              <div>
                <span className="schedule-time-badge">Morning</span>
                <div style={{ fontSize: '0.95rem', fontWeight: 700, marginTop: '0.35rem' }}>
                  Metformin 500 mg
                </div>
                <div style={{ fontSize: '0.78rem', color: 'var(--text-muted)' }}>
                  Take immediately after breakfast
                </div>
              </div>
            </div>

            <div className="schedule-item">
              <Moon size={24} color="#6366f1" />
              <div>
                <span className="schedule-time-badge">Evening</span>
                <div style={{ fontSize: '0.95rem', fontWeight: 700, marginTop: '0.35rem' }}>
                  Metformin 500 mg
                </div>
                <div style={{ fontSize: '0.78rem', color: 'var(--text-muted)' }}>
                  Take immediately after dinner
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* CLINICAL WARNING */}
        <div className="ai-warning-box">
          <AlertTriangle size={20} style={{ flexShrink: 0 }} />
          <span>
            <strong>Medical Notice:</strong> Always follow your doctor's prescription. Do not change dosage without medical advice.
          </span>
        </div>
      </div>

      {/* PROTOTYPE DEMO DISCLAIMER */}
      <div className="prototype-disclaimer">
        ℹ️ Prototype Demonstration Notice: MediTrace AI insights are presented for hackathon evaluation and must be verified by a licensed healthcare provider before clinical decision making.
      </div>

      {/* ACTION BUTTONS */}
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginTop: '0.5rem' }}>
        <button 
          type="button" 
          className="btn btn-secondary" 
          onClick={() => navigate('/upload')}
        >
          <ArrowLeft size={16} />
          <span>Back</span>
        </button>

        <button 
          type="button" 
          className="btn btn-primary btn-lg" 
          onClick={() => navigate('/health-id')}
        >
          <span>Save Record & Continue</span>
          <ArrowRight size={18} />
        </button>
      </div>
    </div>
  );
}
